import type { MetadataRoute } from "next"
import { APP_CONFIG } from "@/lib/app-config"

/**
 * PWA manifest for the marketing site.
 *
 * Next.js App Router serves this file at `/manifest.webmanifest`
 * (or `/manifest.json` depending on the file extension — this file
 * is .ts so Next emits .webmanifest). The browser auto-discovers
 * it via the <link rel="manifest"> tag injected by the root
 * metadata.
 *
 * Icons:
 *   - /icon.svg: existing source of truth, served as SVG.
 *     Browsers that support SVG masks (modern Chrome, Edge,
 *     Firefox) use it directly.
 *   - /apple-icon.png: 180x180 raster for iOS Safari, served
 *     automatically by Next.js from src/app/apple-icon.png.
 *   - /og-icon.png: 32x32 raster for the manifest's "any" size.
 *     Browsers and OSes that don't read SVG fall back to this.
 *
 * The /og-icon.png asset is generated by
 * `apps/web/scripts/generate-favicons.mjs` from the same source
 * SVG, so the visual identity stays single-rooted.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: APP_CONFIG.name,
    short_name: APP_CONFIG.name,
    description: APP_CONFIG.description,
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/apple-icon.png",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/og-icon.png",
        sizes: "32x32",
        type: "image/png",
        purpose: "any",
      },
    ],
  }
}