/**
 * Codegen: read all `.md` snapshots under
 * `src/templates/readmes/` and emit `src/templates/readmes.generated.ts`.
 *
 * Why this codegen exists:
 *   Bundling raw `.md` files at runtime is brittle across consumers
 *   (Next.js' turbopack, pnpm publish from `dist/`, fresh dev installs
 *   from the workspace protocol). The cleanest portable shape is a
 *   TS module that exports the readme strings as literals. This
 *   script runs as part of the package's `prebuild`, emits the
 *   generated file, and the result is committed so consumers never
 *   need to invoke it themselves.
 *
 *   The `.generated.ts` file is committed to the repo. The
 *   `.gitignore` rules ensure it is regenerated deterministically
 *   before each build but stays in version control so the diff
 *   surfaces in PRs.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, "..", "src", "templates", "readmes")
const OUT = join(HERE, "..", "src", "templates", "readmes.generated.ts")

const escape = (s: string): string =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")

const files = readdirSync(SRC)
  .filter((f) => f.endsWith(".md"))
  .sort()

const lines: string[] = []
lines.push("/**")
lines.push(" * Generated by `scripts/generate-readme-snapshot.ts`. DO NOT EDIT.")
lines.push(" *")
lines.push(" * Each entry maps a template slug to its versioned README")
lines.push(" * snapshot. Refresh the source `.md` files via")
lines.push(" * `pnpm refresh-template-readmes` and re-run this codegen.")
lines.push(" */")
lines.push("export const TEMPLATE_READMES: Readonly<Record<string, string>> = {")

for (const file of files) {
  const slug = file.replace(/\.md$/, "")
  const content = readFileSync(join(SRC, file), "utf8")
  lines.push(`  ${JSON.stringify(slug)}: \`${escape(content)}\`,`)
}

lines.push("}")
lines.push("")

writeFileSync(OUT, lines.join("\n"), "utf8")
console.log(`[generate-readme-snapshot] wrote ${files.length} entries`)
