/**
 * Generated by `scripts/generate-readme-snapshot.ts`. DO NOT EDIT.
 *
 * Each entry maps a template slug to its versioned README
 * snapshot. Refresh the source `.md` files via
 * `pnpm refresh-template-readmes` and re-run this codegen.
 */
export const TEMPLATE_READMES: Readonly<Record<string, string>> = {
  "blog-starter": `# Blog Starter

Blog starter with MDX content, syntax highlighting, and OG image generation.

## Stack

- **Framework:** Next.js 16 (App Router)
- **Content:** MDX via content-collections
- **Syntax highlighting:** Shiki + rehype-pretty-code
- **OG images:** \`@vercel/og\` rendered at build time
- **Search:** Pagefind (static)

## Getting started

\`\`\`bash
deessejs init blog-starter
cd blog-starter
pnpm install
pnpm dev
\`\`\`

## Conventions

- Articles live under \`content/posts/{slug}/index.mdx\`
- Authors are first-class types under \`content/authors/\`
- Tag pages are auto-generated
`,
  "docs-starter": `# Docs Starter

Documentation site starter built on Next.js 16 and Fumadocs.

## Stack

- **Framework:** Next.js 16 (App Router)
- **Docs engine:** Fumadocs (MDX content, search, OG images)
- **Search:** Orama (in-process, fully static)
- **LLM endpoints:** llms.txt + per-page markdown
- **Styling:** Tailwind CSS v4

## Getting started

\`\`\`bash
deessejs init docs-starter
cd docs-starter
pnpm install
pnpm dev
\`\`\`

## Highlights

- MDX authoring with Rehype + Shiki for code blocks
- Auto-generated OG images via \`next/og\`
- LLM-friendly routes under \`/llms.txt\` and \`/llms/{slug}.md\`
- Dark mode that respects the system preference
- Versioned docs under \`content/docs/{version}/...\`
`,
  "electron-starter": `# Electron Starter

Production-ready Electron application template with React 19, TanStack Start, Drizzle ORM, and oRPC.

## Stack

- **Shell:** Electron 32
- **UI:** React 19 + TanStack Start
- **Database:** Drizzle ORM (SQLite locally, Postgres in prod)
- **API contracts:** oRPC end-to-end typed
- **Build:** Vite + electron-builder

## Getting started

\`\`\`bash
deessejs init electron-starter
cd electron-starter
pnpm install
pnpm dev
\`\`\`

## What's included

- Auto-update wiring
- Native menus and tray icons
- IPC typed via oRPC contracts shared between main and renderer
- Crash reporting and structured logs
- macOS notarisation scripts
`,
  "eve-starter": `# Eve Starter

Starter template for building, running, and shipping AI agents with eve (by Vercel).

## Stack

- **Framework:** Next.js 16 (App Router)
- **Agent runtime:** eve (Vercel)
- **Model providers:** OpenAI, Anthropic, xAI — swappable via adapters
- **Tool calling:** oRPC end-to-end typed tools

## Getting started

\`\`\`bash
deessejs init eve-starter
cd eve-starter
pnpm install
pnpm dev
\`\`\`

## What's in the box

- Reference agent wired against the Vercel model gateway
- Tooling examples: web search, file fetch, RAG over a Postgres knowledge base
- Streaming UI primitives built on \`react-markdown\`
- Eval harness under \`evals/\` for offline regression
- Tracing via OpenTelemetry-compatible exporters
`,
  "landing-starter": `# Landing Starter

Landing page starter for SaaS and product marketing sites.

## Stack

- **Framework:** Next.js 16 (App Router)
- **Styling:** Tailwind CSS v4 + shadcn/ui primitives
- **Animation:** Framer Motion for hero transitions
- **Forms:** React Hook Form + Zod validation

## Getting started

\`\`\`bash
deessejs init landing-starter
cd landing-starter
pnpm install
pnpm dev
\`\`\`

## Sections pre-wired

- Hero with product preview
- Feature grid
- Pricing comparison table
- Customer logo wall
- FAQ accordion
- Footer with the same diagonal stripes as the rest of the marketing surfaces
`,
  "package-starter": `# Package Starter

TypeScript monorepo template with pnpm workspaces and Turborepo.

## Stack

- **Package manager:** pnpm 9 with workspace protocol
- **Build orchestrator:** Turborepo 2.x
- **Language:** TypeScript 5
- **Testing:** Vitest workspace

## Getting started

\`\`\`bash
deessejs init package-starter
cd package-starter
pnpm install
pnpm build
\`\`\`

## Layout

\`\`\`
packages/
  core/            # shared library
  utils/           # framework-agnostic helpers
  types/           # type-only package
examples/
  basic/           # minimal consumer
\`\`\`

## Tooling

- ESLint flat config preset shared via \`@workspace/eslint-config\`
- Prettier with the \`@trivago/prettier-plugin-sort-imports\` preset
- Changesets for versioning and publishing
- GitHub Actions for CI: lint, typecheck, test, build
`,
  "saas-starter": `# SaaS Starter

Production-ready Next.js boilerplate for B2B SaaS applications.

## Stack

- **Framework:** Next.js 16 (App Router)
- **Auth:** Better Auth + Drizzle ORM
- **Database:** Postgres
- **Styling:** Tailwind CSS v4 + shadcn/ui primitives
- **API:** oRPC end-to-end typed contracts
- **Email:** Resend + react-email
- **Background jobs:** pg-boss

## Getting started

\`\`\`bash
deessejs init saas-starter
cd saas-starter
pnpm install
pnpm dev
\`\`\`

## Features

- Email + password and OAuth sign-in flows (Better Auth)
- Multi-factor authentication scaffold
- Stripe-ready billing primitives
- Playwright integration suite
- Drizzle migrations pre-wired to a local Postgres
- Production-grade rate limiting and session handling

## Documentation

See \`apps/internal-documentation/content/docs/knowledge-base/guides/\` for the full reference, or open the hosted KB at \`/knowledge-base\`.
`,
}
